---
language: ruby
cache: bundler
rvm:
  - 2.1.8
script: bundle exec rake test
branches:
  only:
    - master
matrix:
  include:
  - rvm: 2.3.1
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES=yes
